### PR TITLE
Remove invaild slug

### PR DESCRIPTION
**Pull request by v-xuto**
Remove invalid slug `azure-api-center`.
For more details, you can click link：https://github.com/MicrosoftDocs/samples/blob/main/Azure-Samples/apicenter-reference/.samples-status.json

@justinyoo and @hemarina for notification.

### CODE REVIEW

**Comment by v-xuto** [comment]
@justinyoo Could you help review this PR? If it looks good to you, please help merge it.

**Comment by justinyoo** [comment]
Should we add `azure-apicenter` instead?

**Comment by v-xuto** [comment]
@justinyoo Since `azure-apicenter` does not exist in this [product slugs doc](https://review.learn.microsoft.com/en-us/help/platform/metadata-taxonomies/product?branch=main), it cannot be added. If you insist on adding it, you can submit requests for new slugs `azure-apicenter` according to the steps of this [document](https://review.learn.microsoft.com/en-us/help/platform/metadata-reporting-taxonomy-requests?branch=main).
cc @hemarina

**Comment by justinyoo** [comment]
Thanks for clarification @v-xuto I'll merge it for now. And once the new product slug is added, I'll add it back.

**Pull request merged**
